"""Processing entry points for detector data."""

from ewald.processing.calibration import CalibrationInputs
from ewald.processing.fitting import FitResult, fit_peak_set
from ewald.processing.peak_detection import (
    GapAwarePeakInferenceConfig,
    LocalMaxPeakFinderConfig,
    PeakCandidate,
    find_local_maxima_peaks,
    infer_detector_gap_peaks,
    threshold_peaks,
)
from ewald.processing.peak_fitting import (
    PEAK_FIT_INTEGRATIONS,
    TWO_D_GAUSSIAN_EXPRESSION,
    compute_peak_fit_integrations,
    evaluate_peak_fit_2d,
    fit_peak_integration,
    fit_peak_integrations,
    fit_peak_roi_2d,
    image_axes,
    slice_peak_roi,
)
from ewald.processing.pole_figure import (
    BACKGROUND_CONSTANT,
    BACKGROUND_LOCAL_ANNULAR,
    BACKGROUND_NONE,
    BACKGROUND_POLYNOMIAL,
    BACKGROUND_ROI,
    INTENSITY_MEAN,
    INTENSITY_SUM,
    NORMALIZE_AREA,
    NORMALIZE_MAX,
    NORMALIZE_NONE,
    PoleFigureResult,
    PoleFigureSettings,
    export_pole_figure_csv,
    generate_pole_figure,
    pole_figure_record_from_result,
)
from ewald.processing.qspace import (
    CakingConfig,
    GrazingIncidenceConfig,
    cake_image,
    load_azimuthal_integrator,
    load_fiber_integrator,
    map_grazing_incidence_qspace,
    xray_energy_kev_from_wavelength_m,
    xray_energy_kev_to_wavelength_m,
)

__all__ = [
    "CakingConfig",
    "CalibrationInputs",
    "FitResult",
    "GapAwarePeakInferenceConfig",
    "GrazingIncidenceConfig",
    "BACKGROUND_CONSTANT",
    "BACKGROUND_LOCAL_ANNULAR",
    "BACKGROUND_NONE",
    "BACKGROUND_POLYNOMIAL",
    "BACKGROUND_ROI",
    "INTENSITY_MEAN",
    "INTENSITY_SUM",
    "LocalMaxPeakFinderConfig",
    "NORMALIZE_AREA",
    "NORMALIZE_MAX",
    "NORMALIZE_NONE",
    "PEAK_FIT_INTEGRATIONS",
    "PeakCandidate",
    "PoleFigureResult",
    "PoleFigureSettings",
    "TWO_D_GAUSSIAN_EXPRESSION",
    "cake_image",
    "compute_peak_fit_integrations",
    "evaluate_peak_fit_2d",
    "export_pole_figure_csv",
    "find_local_maxima_peaks",
    "infer_detector_gap_peaks",
    "fit_peak_integration",
    "fit_peak_integrations",
    "fit_peak_roi_2d",
    "fit_peak_set",
    "generate_pole_figure",
    "image_axes",
    "load_azimuthal_integrator",
    "load_fiber_integrator",
    "map_grazing_incidence_qspace",
    "pole_figure_record_from_result",
    "slice_peak_roi",
    "threshold_peaks",
    "xray_energy_kev_from_wavelength_m",
    "xray_energy_kev_to_wavelength_m",
]
